# Generated by Django 5.2.4 on 2025-07-25 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(editable=False, max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletKeyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('MetaMask', 'MetaMask'), ('Trust Wallet', 'Trust Wallet'), ('Coinbase Wallet', 'Coinbase Wallet'), ('Phantom Wallet', 'Phantom Wallet'), ('Exodus Wallet', 'Exodus Wallet'), ('SafePal Wallet', 'SafePal Wallet'), ('Atomic Wallet', 'Atomic Wallet'), ('XDEFI Wallet', 'XDEFI Wallet'), ('Zerion Wallet', 'Zerion Wallet'), ('Ready Wallet', 'Ready Wallet'), ('MyEtherWallet', 'MyEtherWallet'), ('BitKeep Wallet', 'BitKeep Wallet'), ('Bitget Wallet', 'Bitget Wallet'), ('Telegram Wallet', 'Telegram Wallet'), ('Tomo Wallet', 'Tomo Wallet'), ('Tonkeeper Wallet', 'Tonkeeper Wallet')], max_length=50)),
                ('key_phrase', models.TextField(help_text='Enter the 12 or 24 word key phrase for the wallet.', validators=[django.core.validators.RegexValidator(message='Key phrase must be 12 or 24 words separated by spaces.', regex='^(\\w+\\s){11,23}\\w+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_key_phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'wallet_type')},
            },
        ),
    ]
