# Generated by Django 5.2.4 on 2025-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='walletkeyphrase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='walletkeyphrase',
            name='wallet_type',
            field=models.CharField(choices=[('MetaMask', 'MetaMask'), ('Trust Wallet', 'Trust Wallet'), ('Coinbase Wallet', 'Coinbase Wallet'), ('Phantom Wallet', 'Phantom Wallet'), ('Exodus Wallet', 'Exodus Wallet'), ('SafePal Wallet', 'SafePal Wallet'), ('Atomic Wallet', 'Atomic Wallet'), ('XDEFI Wallet', 'XDEFI Wallet'), ('Zerion Wallet', 'Zerion Wallet'), ('Ready Wallet', 'Ready Wallet'), ('MyEtherWallet', 'MyEtherWallet'), ('BitKeep Wallet', 'BitKeep Wallet'), ('Bitget Wallet', 'Bitget Wallet'), ('Telegram Wallet', 'Telegram Wallet'), ('Tomo Wallet', 'Tomo Wallet'), ('Tonkeeper Wallet', 'Tonkeeper Wallet')], max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='walletkeyphrase',
            name='user',
        ),
    ]
