# Generated by Django 5.2.4 on 2025-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_walletkeyphrase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletkeyphrase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
