# Generated by Django 5.2.4 on 2025-07-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_walletkeyphrase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletkeyphrase',
            name='status',
        ),
    ]
