# Generated by Django 5.2.4 on 2025-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_walletkeyphrase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletkeyphrase',
            name='wallet_type',
            field=models.CharField(max_length=100),
        ),
    ]
